-- 코드를 입력하세요
SELECT ANIMAL_ID, NAME
FROM (SELECT A.ANIMAL_ID, A.NAME, B.DATETIME - A.DATETIME AS RESULT
        FROM ANIMAL_INS A JOIN ANIMAL_OUTS B
        ON (A.ANIMAL_ID = B.ANIMAL_ID)
        ORDER BY RESULT DESC)
WHERE ROWNUM <= 2;
