SELECT NAME, DATETIME
FROM (SELECT ROW_NUMBER() OVER (ORDER BY A.DATETIME) AS RN, A.NAME NAME, A.DATETIME DATETIME
      FROM ANIMAL_INS A LEFT OUTER JOIN ANIMAL_OUTS B
      ON (A.ANIMAL_ID = B.ANIMAL_ID)
      WHERE B.ANIMAL_ID IS NULL
      ORDER BY A.DATETIME)
WHERE RN <= 3;