-- 코드를 입력하세요
SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR A JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
ON (A.CAR_ID = B.CAR_ID)
WHERE CAR_TYPE = '세단' 
AND TO_DATE('2022-10-01', 'YYYY-MM-DD') <= START_DATE
AND START_DATE < ADD_MONTHS(TO_DATE('2022-10-01', 'YYYY-MM-DD'), 1)
ORDER BY A.CAR_ID DESC;